Default: &defaults
  database: deiko-pubsubhubbub.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: deiko-pubsubhubbub_test.sqlite3
  <<: *defaults

Staging:
  database: deiko-pubsubhubbub_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: deiko-pubsubhubbub_production.sqlite3
  poolsize: 100
  <<: *defaults
